final/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.auth.views import LoginView as login
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('miscosas/', include('miscosas.urls')),
    path('admin/', admin.site.urls),
    path('login', login.as_view()),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

miscosas/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('loggedIn', views.loggedIn,name='loggedIn'),
    path('logout', views.logout_view, name='logOut'),
    path('profilePhoto/<str:user_name>', views.profilePhoto, name='profilePhoto'),
    path('new/', views.new_user, name='new_user'),
    path('', views.index, name='home'),
    path('alimentadores', views.alimentadores, name='alimentadores'),
    path('alimentadores/<str:alim_id>', views.alimentador_info, name='alimentador_info'),
    path('item/<str:item_id>', views.item, name='item_info'),
    path('users', views.users, name='users'),
    path('user/<str:user_id>', views.user_info, name='user_info'),
    path('new_comment/<str:item_id>', views.item_comment, name='item_comment'),
    path('info', views.info, name='info'),
]

miscosas/models.py
from django.db import models
from django.contrib.auth.models import User

class Alimentador(models.Model):
    name = models.CharField(max_length=256)
    link = models.CharField(max_length=256)
    id = models.CharField(max_length=256, primary_key = True)
    selected = models.BooleanField(default=True)
    puntuacion = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.link

class Item(models.Model):
    alimentador = models.ForeignKey(Alimentador, on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    link = models.CharField(max_length=256)
    description = models.CharField(max_length=256)
    id = models.CharField(max_length=256, primary_key = True)
    puntuacion = models.IntegerField(blank=True, null=True)
    votos_positivos = models.IntegerField(blank=True, null=True)
    votos_negativos = models.IntegerField(blank=True, null=True)
    def __str__(self):
        return self.link


class Comentario(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    cuerpo = models.TextField(blank=False)
    fecha = models.DateTimeField('publicado')

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    thumbsUp = models.BooleanField(default=False)
    thumbsDown = models.BooleanField(default=False)

class ProfilePhoto (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    foto_perfil = models.ImageField(upload_to='miscosas/media/', blank=True, null=True)

miscosas/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import ProfilePhoto, Comentario

class UsersForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username','email', 'password',)


class PhotoForm(forms.ModelForm):

    class Meta:
        model = ProfilePhoto
        fields = ('foto_perfil',)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comentario
        exclude = ['user', 'item', 'fecha']

miscosas/views.py
from django.shortcuts import render, get_object_or_404
from urllib.request import urlopen
from .ytchannel import YTChannel
from .redditnews import RedditNews
from .models import Alimentador, Item, Comentario, Vote
from .forms import UsersForm, PhotoForm,CommentForm
from django.shortcuts import redirect
from django.contrib.auth import logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as do_login
from django.utils import timezone

def puntuacion_alim ():
    for alim in Alimentador.objects.all():
        Up = 0
        Down = 0
        for item in alim.item_set.all():
            for voto in item.vote_set.all():
                if voto.thumbsUp:
                    Up = Up +1
                elif voto.thumbsDown:
                    Down = Down +1
        alim.puntuacion = Up - Down
        alim.save()
    alimentadores = Alimentador.objects.order_by('-puntuacion')
    return alimentadores

def puntuacion_item ():
    for item in Item.objects.all():
        # __init__
        item.votos_positivos = 0
        item.votos_negativos = 0
        item.puntuacion = 0

        for voto in item.vote_set.all():
            if voto.thumbsUp:
                item.votos_positivos = item.votos_positivos +1
            elif voto.thumbsDown:
                item.votos_negativos = item.votos_negativos +1
        item.puntuacion = (item.votos_positivos - item.votos_negativos)
        item.save()
    #ordenamos el diccionario
    item_list = Item.objects.order_by('-puntuacion')

    return item_list

def parseYoutube(index):
    xmlStream = urlopen('https://www.youtube.com/feeds/videos.xml?channel_id=' + index)
    link = ('https://www.youtube.com/channel/' + index)
    channel = YTChannel(xmlStream)
    # Comprobamos si ya existe el alimentador
    try:
        alimentador = Alimentador.objects.get(link=channel.uriAlim())
    except Alimentador.DoesNotExist:
        alimentador = Alimentador(name= channel.nameAlim(),
                      link=channel.uriAlim(), id = index)
        alimentador.save()
    # Igualmente actualizamos
    for video in channel.videos():
        video = Item(alimentador = alimentador, title=video['title'],
                      link=video['link'], description = video['description'], id = video['id'])
        video.save()

def parseReddit(index):
    xmlStream = urlopen('https://www.reddit.com/r/' + index + '.rss')
    link = ('https://www.reddit.com/r/' + index )
    subreddit = RedditNews(xmlStream)
    # Comprobamos si ya existe el alimentador
    try:
        alimentador = Alimentador.objects.get(name = subreddit.nameAlim())
    except Alimentador.DoesNotExist:
        alimentador = Alimentador(name= subreddit.nameAlim(),
                      link=subreddit.uriAlim(), id = index)
        alimentador.save()
    # Igualmente actualizamos
    for new in subreddit.news():
        new = Item(alimentador = alimentador, title=new['title'],
                      link=new['link'], description = new['description'], id = new['id'])
        new.save()



def index(request):
    if request.method == "POST":
        # ¿De que alimentados procede?
        action = request.POST['action']
        # YOUTUBE
        if action == "Enseñame el canal":
            id = request.POST['valor']
            if not id or id[0] == " ":
                return render(request, 'miscosas/noContent.html')
            else:
                parseYoutube(id)

        elif action == "Dame las noticias":
            name = request.POST['valor']

            if not name or name[0] == " ":
                return render(request, 'miscosas/noContent.html')
            else:
                parseReddit(name)

        elif action == "Eliminar":
            alim_id = request.POST['alim_id']
            alimentador = Alimentador.objects.get(id = alim_id)
            alimentador.selected = False
            alimentador.save()
            return redirect('/miscosas/')

        elif action == "Selecionar":
            alim_id = request.POST['alim_id']
            alimentador = Alimentador.objects.get(id = alim_id)
            # Es youtbe o es reddit
            if alimentador.link[12:19] == "youtube":
                parseYoutube(alimentador.id)
            else:
                parseReddit(alimentador.id)

        alimentadores_list = Alimentador.objects.all()
        context = {'alimentadores_list': alimentadores_list}
        return redirect('/miscosas/alimentadores')
    elif request.method == "GET":
        # puntuacion de los items
        item_list = puntuacion_item()
        # alimentadores
        alimentadores_list = puntuacion_alim ()  # actualizamos las puntuaciones
        votes = None
        if request.user.is_authenticated:
            try:
                votes = request.user.vote_set.order_by('id')
                votes = request.user.vote_set.all()[:6]

            except Vote.DoesNotExist:
                votes = None
        context = {'item_list': item_list[:10],'alimentadores_list': alimentadores_list,'votes':votes}
        # puntuacion de los alimentadores
        return render(request, 'miscosas/index.html', context)

def alimentadores(request):
    alimentadores_list = Alimentador.objects.all()
    alimentadores_list = puntuacion_alim ()  # actualizamos las puntuaciones
    context = {'alimentadores_list': alimentadores_list}
    return render(request, 'miscosas/alimentadores.html', context)

def alimentador_info(request, alim_id):
    if request.method == "GET":
        try:
            alimentador = Alimentador.objects.get(id = alim_id)
        except Alimentador.DoesNotExist:
            return render(request, 'miscosas/noContent.html')
        context = {'alimentador': alimentador}
        return render(request, 'miscosas/alimentador_info.html', context)
    elif request.method == "POST":
        action = request.POST['select']
        alim_id = request.POST['alim_id']
        alimentador = Alimentador.objects.get(id = alim_id)
        if action == "Deseleccionar":
            alimentador.selected = False
        elif action == "Seleccionar":
            alimentador.selected = True
        alimentador.save()
        return redirect(request.path)



def item(request, item_id):
    if request.method == "GET":
        item = Item.objects.get(id = item_id)
        # Es youtbe o es reddit
        alim = item.alimentador.link[12:19] == "youtube"
        voto = None
        if request.user.is_authenticated:
            try:
                voto = Vote.objects.get(item = item, user = request.user)
            except Vote.DoesNotExist:
                voto = Vote(user= request.user,
                              item=item)
                voto.save()
        context = {'item': item, 'alim': alim, 'voto': voto}
        return render(request, 'miscosas/item_info.html', context)

    elif request.method == "POST":
        item_id = request.POST['item_id']
        item = get_object_or_404(Item, id = item_id)
        voto = get_object_or_404(Vote, item = item, user = request.user)

        action = request.POST['thumbs']
        if action == "Up" and voto.thumbsDown:
            voto.thumbsDown = False
            voto.thumbsUp = True
        elif action == "Down" and voto.thumbsUp:
            voto.thumbsDown = True
            voto.thumbsUp = False
        elif not (voto.thumbsDown and voto.thumbsUp):
            if action == "Up":
                voto.thumbsUp = True
            elif action == "Down":
                voto.thumbsDown = True
        voto.save()
        # recuento de votos
        puntuacion_item()
        # alimentadores
        puntuacion_alim ()  # actualizamos las puntuaciones
        return redirect(request.path)
    return(request.path)


def users(request):
    users_list = User.objects.all()
    context = {'users_list': users_list}
    return render(request, 'miscosas/users.html', context)

def user_info(request, user_id):
    user = User.objects.get(username = user_id)

    context = {'usuario': user,}
    return render(request, 'miscosas/user.html', context)

def new_user(request):
    if request.method == "POST":
        form = UsersForm(request.POST)
        if form.is_valid():
            user = form.save()
            do_login(request, user)
            return redirect('/miscosas/user/' + user.username)
    else:
        form = UsersForm()
    return render(request, 'miscosas/new_user.html', {'form': form})

def profilePhoto(request, user_name):
    if request.method == "POST":
        user = User.objects.get(username = user_name)
        form = PhotoForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('/miscosas')

    else:
        form = PhotoForm()
    return render(request, 'miscosas/new_user.html', {'form': form})

def loggedIn(request):
    # Creamos el formulario de autenticación vacío
    form = AuthenticationForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = AuthenticationForm(data =request.POST)

        # Recuperamos las credenciales validadas
        username = request.POST['username']
        password = request.POST['password']
        # Verificamos las credenciales del usuario
        try:
            user = User.objects.get(username=username, password=password)
        except User.DoesNotExist:
            return render(request, "miscosas/login.html", {'form': form})

        # Si existe un usuario con ese nombre y contraseña
        if user is not None:
            # Hacemos el login manualmente
            do_login(request, user)
            # Y le redireccionamos a la portada
            return redirect('/miscosas')

    # Si llegamos al final renderizamos el formulario
    return render(request, "miscosas/login.html", {'form': form})

def logout_view(request):
    logout(request)
    return redirect("/miscosas/")
def info(request):

miscosas/templates/miscosas/alimentador_info.html
{% extends 'miscosas/base.html' %}

{% block contenido %}

<br>
<div class="w3-container w3-row w3-center w3-dark-grey">
  <i class=" 	fa fa-diamond w3-margin-top w3-jumbo"></i>
  <h1>{{ alimentador.name }}</h1>
  <p class="w3-center w3-large"><a href="{{ alimentador.link }}">{{ alimentador.link }}</a></p>
  <p class="w3-center w3-large">Numero de items disponibles: {{alimentador.item_set.count}}</p>
  <div class="w3-center">
    <form method="POST">
    {% csrf_token %}
    <input type='hidden' name='alim_id' value='{{alimentador.id}}'>
    {%  if alimentador.selected %}
      <button class ="save btn btn-info" name = 'select' value = "Deseleccionar">Deseleccionar
      </button>
    {%elif not alimentador.selected%}
      <button class ="save btn btn-info" name = 'select' value = "Seleccionar">Seleccionar
      </button>
      {%else%}
        error
    {%endif%}</form>
  </div>

</div>


<div class="w3-container w3-center" style="padding:0px 16px" id="misvotos">

  <div class="w3-row-padding w3-center" style="margin-top:64px">
    {% if  alimentador.item_set.all  %}
      {% for item in alimentador.item_set.all %}
      <div class="w3-third"  style="margin-top:64px">
        <i class="w3-margin-bottom w3-jumbo w3-center"></i>
        <p class="thick"><a href="{% url 'item_info' item_id=item.id%}">{{ item.title }}</a></p>
        <p style="color:DodgerBlue;"><a href="{{ item.link }}">{{ item.link }}</a></p>
      </div>

      {% endfor %}
    {% else %}
        <p>Contenido no disponible.</p>
    {% endif %}
  </div>
</div>

{% endblock %}

miscosas/templates/miscosas/alimentadores.html
{% extends 'miscosas/base.html' %}

{% block contenido %}
<div class="w3-container w3-row w3-center w3-dark-grey w3-padding-64">
  <i class="fa fa-share w3-margin-top w3-jumbo"></i>
  <h1 class="w3-center">Alimentadores</h1>
</div>


<div class="w3-container w3-center" style="padding: 16px">
  <i class="w3-margin-bottom w3-jumbo"></i>
  <div class="w3-row-padding" style="margin-top:64px">
    {% if alimentadores_list  %}
      {% for alimentador in alimentadores_list %}
        <div class="w3-third"  style="margin-top:64px">
          <i class="w3-margin-bottom w3-jumbo w3-center"></i>
          <p><a href="{% url 'alimentador_info' alim_id=alimentador.id%}">{{ alimentador.name }}</a></p>
          <p style="color:DodgerBlue;"><a href="{{ alimentador.link }}">{{ alimentador.link }}</a></p>
          <p>Items disponibles: {{alimentador.item_set.count}}</p>
          <p>Puntuacion: {{alimentador.puntuacion}}</p>
        </div>
      {% endfor %}
    {% else %}
        <p>Contenido no disponible.</p>
    {% endif %}
  </div>
</div>


{% endblock %}

miscosas/templates/miscosas/base.html
{% load static %}
<html>
  <head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}

    body, html {
      height: 100%;
      line-height: 1.8;
    }

    /* Full height image header */
    .bgimg-1 {
      background-position: center;
      background-size: cover;
      min-height: 100%;
    }
    p.thick {
      font-weight: 1000;
    }

    .w3-bar .w3-button {
      padding: 16px;
    }
  </style>

  <title>Final</title>
</head>
<body>
  <div class="w3-top">
    <div class="w3-bar w3-white w3-card">
      <a class="w3-bar-item w3-wide w3-logo">Mis Cosas</a>
      <div class="w3-center w3-hide-small">
        {%  if user.is_authenticated %}
          <a class="w3-button" href="{% url 'logOut' %}">¡Log Out!</a>
        {% else %}
          <a class="w3-button" href="{% url 'new_user' %}">¡Darme de alta!</a>
          <a class="w3-button" href="{% url 'loggedIn' %}">¡Log In!</a>
        {%  endif %}
        {% if request.path == '/miscosas/' %}
          <div class="w3-right w3-hide-small">
            <a href="#top" class="w3-bar-item w3-button">TOP</a>
            <a href="#forms" class="w3-bar-item w3-button">FORMS</a>
            <a href="#alimentadores" class="w3-bar-item w3-button"> ALIMENTADORES</a>
            {%if user.is_authenticated%}
              <a href="#misvotos" class="w3-bar-item w3-button"> MIS VOTOS</a>
            {%endif%}
          </div>
        {%  endif %}
      </div>
    </div>
  </div>
  <!-- Menú -->
  <div class="w3-container w3-bar w3-card" style="margin-top:64px" id = "menu">
    <div class="w3-row-padding w3-center">
      {% if request.path != '/miscosas/' %}
        <div class="w3-quarter">
          <i class="w3-margin-bottom w3-jumbo w3-center"></i>
          <p><a href="{% url 'home'%}" class="w3-button w3-white w3-padding-large w3-large w3-opacity w3-hover-opacity-off">Inicio</a></p>
        </div>
      {%endif%}
      {% if '/alimentadores' not in request.path %}
        <div class="w3-quarter">
          <i class="w3-margin-bottom w3-jumbo w3-center"></i>
          <p><a href="{% url 'alimentadores'%}" class="w3-button w3-white w3-padding-large w3-large w3-opacity w3-hover-opacity-off">Alimentadores</a></p>
        </div>
      {%endif%}
      {% if '/users' not in request.path %}
        <div class="w3-quarter">
          <i class="w3-margin-bottom w3-jumbo"></i>
          <p><a href="{% url 'users'%}" class="w3-button w3-white w3-padding-large w3-large w3-margin-top w3-opacity w3-hover-opacity-off">Usuarios</a></p>
        </div>
      {%endif%}
      {% if '/info' not in request.path %}
        <div class="w3-quarter">
          <i class="w3-margin-bottom w3-jumbo"></i>
          <p><a href="{% url 'info'%}" class="w3-button w3-white w3-padding-large w3-large w3-margin-top w3-opacity w3-hover-opacity-off">Informacion</a></p>
        </div>
      {%endif%}
    </div>
  </div>

  {% block contenido %}



  {% endblock %}

  <!-- Footer -->
  <footer class="w3-center w3-black w3-padding-64">
    <a href="#menu" class="w3-button w3-light-grey"><i class="fa fa-arrow-up w3-margin-right"></i>Volver arriba.</a>
    <div class="w3-xlarge w3-section">
      <p>Powered by</p>
      <div class="w3-xlarge w3-section">
        <p><a href="https://www.youtube.com/">Youtube</a>   &   <a href="https://www.reddit.com/">Reddit</a></p>
      </div>
    </div>
  </footer>

</body>

miscosas/templates/miscosas/info.html
{% extends 'miscosas/base.html' %}


{% block contenido %}


  <div class="w3-center w3-large">
    <div class="w3-container w3-dark-grey">
      <i class="fa fa-info w3-margin-top w3-jumbo"></i>
      <h3>Página de información</h3>
      <p>Te contamos más acerca de nuestro proyecto.</p>
    </div>
    <div class="w3-container" style="padding:0px 56px">
      <i class="w3-margin-bottom w3-jumbo"></i>
      <p>Esta web es fruto de la práctica final de la asignatura Servicios y Aplicaciones Telemáticas de la ETSIT. Universidad
      Rey Juan Carlos.</p>
      <p> Trabajamos con Youtube y Reddit para alimentar nuestra aplicación. En ella podrás almacenar inforcación
      en forma de canales de youtube y noticias de Reddit a las que llamaremos alimentadores. Tras haber elegido un alimentador la aplicación
      descargará en su base de datos los vídeos (en caso de Youtube) y noticias (en caso de Reddit) que ese canal o subreddit contenga.
      A cada video o subreddit lo llamaremos item, el cual podrás comentar y votar en el caso que seas usuario de la comunidad. Puedes darte
      de alta gratuitamente en el baner superior de la aplicación.  </p>
      <p>¡Bienvenido a Mis Cosas y disfruta de la experiencia!</p>
      <p>Fdo. Equipo técnico</p>
      <p>Autoría: Rocío Díaz Fernández.</p>

    </div>
  </div>

{% endblock %}

miscosas/templates/miscosas/item_info.html
{% extends 'miscosas/base.html' %}

{% block contenido %}

  <br>
  <div class="w3-container w3-row w3-center w3-dark-grey w3-padding-64">
    <i class=" fa fa-anchor w3-margin-bottom w3-jumbo"></i>

    <h1>{{ item.title }}</h1>
    <p class="w3-center w3-large"><a href="{{ item.link }}">{{ item.link }}</a></p>
  </div>

  <div class="w3-container w3-row w3-center w3-padding-64">
    <div class="w3-container w3-row w3-center w3-half ">
      <h2>DESCRIPCIÓN</h2> <br> <p class="w3-center w3-large">{{item.description|safe}}</p>
      <div class="w3-container w3-row w3-center w3-padding-64">
        {%  if user.is_authenticated %}
          {% include "miscosas/vote_subtemp.html" %}
        {%endif%}

      </div>

    </div>
    {%if alim%}
      <div class="w3-container w3-row w3-center w3-half ">
        <iframe width="560" height="315"
          src="https://www.youtube.com/embed/{{item.id }}"
          frameborder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen></iframe>
      </div>
    {%endif%}

  </div>

  <hr>

  <div class="w3-container w3-center" style="padding:128px 16px" id="team">
    <i class="  	fa fa-comments w3-margin-bottom w3-jumbo"></i>
    <h3 class="w3-center">COMENTARIOS</h3>
    <div class="w3-row-padding w3-grayscale" style="margin-top:64px">
      {%if item.comentario_set.all%}
        {%  for comentario in item.comentario_set.all %}

        <div class="w3-col l3 m6 w3-margin-bottom">
          <div class="w3-card">
            <div class="w3-container">
              <h3>{{  comentario.user.username }}</h3>
              <p class="w3-opacity">{{ comentario.fecha }}</p>
              <p class="w3-center w3-large" >{{  comentario.cuerpo|linebreaksbr }}</p>

            </div>
          </div>
        </div>

        {% endfor %}
      {%else%}
        <p class="w3-center w3-large">No hay comentarios aún. ¡Prueba a escribir uno! Recuerda que para escribir un comentario debes estar logeado</p>
      {%endif%}
    </div>
    {%  if user.is_authenticated %}
      <button type="button"  class="w3-center btn btn-light"><a href="{% url 'item_comment' item_id=item.id %}">¡Añadir un comentario!</span></a></button>
    {%endif%}
  </div>

  <hr>

  <div class="w3-container w3-center w3-row w3-rigth w3-dark-grey w3-padding-64">
    <h1>ALIMENTADOR</h1>
    <div class="w3-quarter">
      <p><a href="{% url 'alimentador_info' alim_id=item.alimentador.id%}">{{item.alimentador.name }}</a></p>
    </div>
    <div class="w3-quarter">
      <p><a href="{{ item.alimentador.link }}">{{item.alimentador.link }}</a></p>
    </div>
    <div class="w3-quarter">
      <p>Items disponibles: {{item.alimentador.item_set.count}}</p>
    </div>
    <div class="w3-quarter">
      <p>Puntuacion: {{item.alimentador.puntuacion}}</p>
    </div>



  </div>


{% endblock %}

miscosas/templates/miscosas/user.html
{% extends 'miscosas/base.html' %}

{% block contenido %}
<div class="w3-container w3-row w3-center w3-dark-grey w3-padding-64">
  <h1 class="w3-center">{{usuario.username}}</h1>
</div>
<hr>


  <div class="w3-container w3-center" style="padding:128px 16px" id="top">
    <i class="fa fa-heart w3-margin-bottom w3-jumbo"></i>
    <h3 class="w3-center">Items votados</h3>
    <div class="w3-row-padding w3-center" style="margin-top:64px">

      {% for voto in usuario.vote_set.all %}
        <div class="w3-third w3-card">
          <i class= w3-margin-bottom w3-jumbo w3-center"></i>
          <p class="w3-center w3-large"><a href="{% url 'item_info' item_id=voto.item.id%}">{{ voto.item.title }}</a></p>
          <p class="w3-center w3-large"><a href="{{ voto.item.link }}"> {{ voto.item.link }}</a></p>
          <p class="w3-center w3-large">Votos positivos: {{voto.item.votos_positivos}} || Votos negativos:{{voto.item.votos_negativos}}</p>
        </div>
      {% endfor %}

    </div>
  </div>

  <hr>
  <div class="w3-container w3-center" >
    <i class="  	fa fa-comments w3-margin-bottom w3-jumbo"></i>
    <h3 class="w3-center">ITEMS COMENTADOS</h3>
    <div class="w3-row-padding w3-center">
      {%if usuario.comentario_set.all%}
        {% for comentario in usuario.comentario_set.all %}

          <div class="w3-third w3-card">
            <i class= w3-margin-bottom w3-jumbo w3-center"></i>
            <p class="w3-center w3-large"><a href="{% url 'item_info' item_id=comentario.item.id%}">{{ comentario.item.title }}</a></p>
            <p class="w3-center w3-large"><a href="{{ comentario.item.link }}"> {{ comentario.item.link }}</a></p>
            <p class="w3-center w3-large">Votos positivos: {{comentario.item.votos_positivos}} || Votos negativos:{{comentario.item.votos_negativos}}</p>
          </div>
          {% endfor %}

          </div>

      {%else%}
        <p class="w3-center w3-large">Este usuario no ha comentado ningún item</p>
      {%endif%}

    </div>
  </div>


  <br>
  {% if usuario.is_authenticated and user.username == usuario.username%}
<hr>
    <div class="w3-container w3-center" >
      <p class="w3-center w3-large">Cambia la foto de perfil:</p>
      <button type="button"  class="btn btn-light"><a href="{% url 'profilePhoto' user_name=user%}">Foto de perfil</span></a></button>
    </div>
  {% endif %}

{% endblock %}

miscosas/templates/miscosas/users.html
{% extends 'miscosas/base.html' %}

{% block contenido %}

<div class="w3-container w3-row w3-center w3-dark-grey w3-padding-64">
  <i class="fa fa-odnoklassniki w3-margin-top w3-jumbo"></i>

  <h1 class="w3-center">Usuarios</h1>
</div>


<div class="w3-container w3-center" style="padding:56px 16px" id="team">
  <div class="w3-row-padding w3-grayscale" style="margin-top:64px">
    {%if users_list%}
      {%  for user in users_list %}
        <div class="w3-col l3 m6 w3-margin-bottom">
          <div class="w3-card">
            <img src="{{ user.profilePhoto_set.foto_perfil.url }}" style="width:100%"/>
            <div class="w3-container">
              <h3><a href="{% url 'user_info' user_id=user.username%}">{{user.username}}</a></h3>
              <p class="w3-center w3-large" >Total de comentarios:{{  user.comentario_set.count}}</p>
              <p class="w3-center w3-large" >Total de items votados:{{  user.vote_set.count}}</p>
            </div>
          </div>
        </div>

      {% endfor %}
    {%else%}
      <p class="w3-center w3-large">¡No hay ningún usuario registrado!</p>
    {%endif%}
  </div>

</div>

{% endblock %}